remote_theme: danielknox/spacefinder
title: Space Finder - University of Kent
email: d.knox@kent.ac.uk
description: >-
  Spacefinder is an application designed for students
  to locate study spaces at the University of Leeds. It
  includes detailed descriptions of each space, filters
  based on space characteristics, and  navigation via a
  map.
environment: production
baseurl: ""
url: "https://danielknox.github.io/spacefinder.kent.ac.uk"
host: "localhost"
google_analytics: ""
photo_dir: "/assets/photos/"
lang: "en"
dc:
  creator: "University of Leeds"
  dateCreated: "2022-06-06"
  dateModified: "2023-12-18"
  publisher: "University of Kent"
  spatialCoverage: "University of Kent campus"
  types:
    - "InteractiveResource"
  subjects:
    - "Digital mapping"
    - "College Campuses"
terms:
  url: "https://www.leeds.ac.uk/termsandconditions"
  text: "Terms &amp; Conditions"
  shorttext: "Terms"
foi:
  url: "https://www.kent.ac.uk/about/assurance-and-data-protection/freedom-of-information-requests"
  text: "Freedom of Information"
  shorttext: "FOI"
copyright: "University of Leeds"
sass:
  style: compressed
plugins:
  - jekyll-feed
