name: cron-updates
on:
  schedule:
    - cron: '5 4 * * *'
jobs:
  keep_file_updated:
    runs-on: ubuntu-latest
    name: Run daily cron
    steps:
      - uses: actions/checkout@v3
        with:
          path: main
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Update and commit
        run: | 
          cd main
          npm run crontab
          npm run concat
          git config --global user.name 'peteredwards'
          git config --global user.email 'p.l.edwards@leeds.ac.uk'
          git add --all
          git diff-index --quiet HEAD || (git commit -am "[bot] Updated space data using crontab" && git push)
