name: get-library-opening-hours-manual
on: workflow_dispatch
jobs:
  keep_file_updated:
    runs-on: ubuntu-latest
    name: Run daily update of opening hours
    steps:
      - uses: actions/checkout@v3
        with:
          path: main
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Update and commit
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: | 
          cd main
          npm run libcal
          npm run concat
          git config --global user.name 'peteredwards'
          git config --global user.email 'p.l.edwards@leeds.ac.uk'
          git add --all
          git diff-index --quiet HEAD || (git commit -am "[bot] Updated space data using crontab" && git push)
