name: update-hours-from-libcal-data
on:
  schedule:
    - cron: '10 5 * * *'
jobs:
  update-opening:
    runs-on: ubuntu-latest
    name: Run daily update of spaces from opening hours data
    steps:
      - uses: actions/checkout@v3
        with:
          path: main
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Update and commit
        run: | 
          cd main
          npm run updateHours
          npm run concat
          git config --global user.name 'peteredwards'
          git config --global user.email 'p.l.edwards@leeds.ac.uk'
          git add --all
          git diff-index --quiet HEAD || (git commit -am "[bot] Library Opening Hours updated from LibCal data" && git push)
