name: update-library-opening-hours
on: workflow_dispatch
jobs:
  update-opening:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: main
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Update and commit
        run: | 
          cd main
          npm run updateOpening
          npm run concat
          git config --global user.name 'peteredwards'
          git config --global user.email 'p.l.edwards@leeds.ac.uk'
          git add --all
          git diff-index --quiet HEAD || (git commit -am "Library Opening Hours updated from calendar JSON feed" && git push)
